# Generated by Django 6.0.2 on 2026-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_period', models.CharField(max_length=50)),
                ('train_station_name', models.CharField(max_length=255)),
                ('rail_direction', models.CharField(max_length=255)),
                ('train_number', models.CharField(max_length=50)),
                ('observations_count', models.IntegerField()),
                ('on_time_count', models.IntegerField()),
                ('on_time_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
