# Generated by Django 6.0.2 on 2026-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvergenceBusToRail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_period', models.CharField(max_length=50)),
                ('train_station_name', models.CharField(max_length=255)),
                ('rail_direction', models.CharField(max_length=255)),
                ('train_number', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=255)),
                ('makat', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('alternative', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=32)),
                ('avg_passengers_per_trip', models.FloatField(blank=True, null=True)),
                ('arrival_time_to_station', models.CharField(blank=True, max_length=32)),
                ('arrival_time_window', models.CharField(blank=True, max_length=255)),
                ('minutes_gap_bus_to_rail', models.FloatField(blank=True, null=True)),
                ('recommended_minutes', models.IntegerField(blank=True, null=True)),
                ('observations_count', models.IntegerField(blank=True, null=True)),
                ('on_time_count', models.IntegerField(blank=True, null=True)),
                ('on_time_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConvergenceRailToBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_period', models.CharField(max_length=50)),
                ('train_station_name', models.CharField(max_length=255)),
                ('rail_direction', models.CharField(max_length=255)),
                ('train_number', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=255)),
                ('makat', models.CharField(blank=True, max_length=50)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('alternative', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=32)),
                ('avg_passengers_per_trip', models.FloatField(blank=True, null=True)),
                ('train_departure_time', models.CharField(blank=True, max_length=32)),
                ('minutes_gap_rail_to_bus', models.FloatField(blank=True, null=True)),
                ('recommended_minutes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConvergenceRecord',
        ),
        migrations.AddConstraint(
            model_name='convergencebustorail',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'week_period', 'train_station_name', 'rail_direction', 'train_number', 'makat', 'departure_time'), name='uniq_cov_b2r_row'),
        ),
        migrations.AddConstraint(
            model_name='convergencerailtobus',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'week_period', 'train_station_name', 'rail_direction', 'train_number', 'makat', 'departure_time'), name='uniq_cov_r2b_row'),
        ),
    ]
