# Generated by Django 6.0.2 on 2026-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0002_convergencebustorail_convergencerailtobus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='is_bus_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencebustorail',
            name='is_gold_train',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='convergencebustorail',
            name='rishui_train_departure_time',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='convergencebustorail',
            name='signage',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='is_bus_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='is_gold_train',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='rishui_train_arrival_time',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='signage',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
