# Generated by Django 6.0.2 on 2026-03-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0003_convergencebustorail_is_bus_on_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergencebustorail',
            name='signage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='convergencebustorail',
            name='train_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='signage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='train_number',
            field=models.IntegerField(),
        ),
    ]
