# Generated by Django 6.0.2 on 2026-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0004_alter_convergencebustorail_signage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergencebustorail',
            name='direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='direction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
