# Generated by Django 6.0.2 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("convergence", "0006_alter_convergencebustorail_makat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convergencebustorail",
            old_name="rishui_train_departure_time",
            new_name="rishui_train_arrival_time",
        ),
    ]
