# Generated by Django 6.0.2 on 2026-03-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0007_rename_b2r_rishui_departure_to_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convergencerailtobus',
            name='train_departure_time',
        ),
    ]
