# Generated by Django 6.0.2 on 2026-03-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0008_remove_convergencerailtobus_train_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='train_ascending_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='train_descending_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
