# Generated by Django 6.0.2 on 2026-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0009_convergencebustorail_train_ascending_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='train_station_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='train_station_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
