# Generated by Django 6.0.2 on 2026-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0010_convergencebustorail_train_station_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM_raw_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_period', models.CharField(max_length=50)),
                ('makat', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('alternative', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=32)),
                ('arrival_time_to_station_raw', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
