# Generated by Django 6.0.2 on 2026-03-24 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0011_vm_raw_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideConv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_period', models.CharField(max_length=50)),
                ('link_direction', models.CharField(max_length=32)),
                ('makat', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('alternative', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=32)),
                ('train_station_code', models.IntegerField()),
                ('from_train_number', models.IntegerField()),
                ('from_train_rishui_train_arrival_time', models.CharField(blank=True, max_length=32)),
                ('to_train_number', models.IntegerField(blank=True, null=True)),
                ('to_train_rishui_train_arrival_time', models.CharField(blank=True, max_length=32)),
                ('effective_month', models.CharField(blank=True, max_length=7)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_enabled', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_by', models.CharField(blank=True, max_length=255)),
                ('disable_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'override_conv',
                'constraints': [models.UniqueConstraint(fields=('week_period', 'link_direction', 'makat', 'direction', 'alternative', 'departure_time', 'train_station_code', 'from_train_number', 'from_train_rishui_train_arrival_time'), name='uniq_override_conv_default_key')],
            },
        ),
    ]
