# Generated by Django 6.0.2 on 2026-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0012_overrideconv'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='on_time_percentage_by_train',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
