# Generated by Django 6.0.2 on 2026-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0013_convergencebustorail_on_time_percentage_by_train'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VM_raw_data',
        ),
        migrations.AlterModelOptions(
            name='overrideconv',
            options={'permissions': [('can_manage_convergence_overrides', 'Can manage convergence overrides')]},
        ),
        migrations.AddField(
            model_name='convergencebustorail',
            name='express_train',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='convergencebustorail',
            name='on_time_percentage_by_train_station',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
