# Generated by Django 6.0.2 on 2026-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0014_delete_vm_raw_data_alter_overrideconv_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='duration_from_current_station_to_hashalom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='duration_from_hashalom_to_current_station',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convergencerailtobus',
            name='express_train',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
