# Generated by Django 6.0.2 on 2026-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0015_convergencebustorail_duration_from_current_station_to_hashalom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawBusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('week_period', models.CharField(max_length=50)),
                ('makat', models.IntegerField(blank=True, null=True)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('alternative', models.CharField(blank=True, max_length=255)),
                ('departure_time', models.CharField(blank=True, max_length=32)),
                ('bus_arrival_time_to_station', models.CharField(blank=True, max_length=32)),
                ('ride_counts', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
