# Generated by Django 6.0.2 on 2026-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0016_rawbusdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawbusdata',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
