# Generated by Django 6.0.2 on 2026-05-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0017_alter_rawbusdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawbusdata',
            name='train_station_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convergencebustorail',
            name='year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
