# Generated by Django 6.0.2 on 2026-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0018_rawbusdata_train_station_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawbusdata',
            name='rail_direction',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
