# Generated by Django 6.0.2 on 2026-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0019_rawbusdata_rail_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='convergencebustorail',
            name='on_time_percentage_by_makat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
