# Generated by Django 6.0.2 on 2026-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0020_convergencebustorail_on_time_percentage_by_makat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergencebustorail',
            name='train_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convergencebustorail',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='train_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rawbusdata',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
