# Generated by Django 6.0.2 on 2026-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0021_alter_convergencebustorail_train_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergencebustorail',
            name='signage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='signage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
