# Generated by Django 6.0.2 on 2026-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0022_alter_convergencebustorail_signage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convergencebustorail',
            name='operator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convergencebustorail',
            name='rail_direction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convergencebustorail',
            name='train_station_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='operator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='rail_direction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convergencerailtobus',
            name='train_station_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
