# Generated by Django 6.0.2 on 2026-06-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0023_alter_convergencebustorail_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overrideconv',
            name='to_departure_time',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
