# Generated by Django 6.0.2 on 2026-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0024_overrideconv_to_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overrideconv',
            name='train_station_code',
        ),
        migrations.AddField(
            model_name='overrideconv',
            name='station_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
