# Generated by Django 6.0.2 on 2026-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convergence', '0025_remove_overrideconv_train_station_code_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE override_conv DROP INDEX uniq_override_conv_default_key",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='overrideconv',
                    name='uniq_override_conv_default_key',
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='overrideconv',
            constraint=models.UniqueConstraint(fields=('week_period', 'link_direction', 'makat', 'direction', 'alternative', 'departure_time', 'station_name', 'from_train_number', 'from_train_rishui_train_arrival_time'), name='uniq_override_conv_default_key'),
        ),
        migrations.RemoveField(
            model_name='overrideconv',
            name='disable_reason',
        ),
        migrations.RemoveField(
            model_name='overrideconv',
            name='disabled_at',
        ),
        migrations.RemoveField(
            model_name='overrideconv',
            name='disabled_by',
        ),
        migrations.RemoveField(
            model_name='overrideconv',
            name='is_enabled',
        ),
    ]
