# Generated by Django 6.0.2 on 2026-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('WeekPeriod', models.CharField(max_length=20)),
                ('train_station_code', models.IntegerField()),
                ('StationName', models.CharField(max_length=255)),
                ('Train_number', models.IntegerField()),
                ('event_type', models.CharField(choices=[('ARRIVAL', 'Arrival'), ('DEPARTURE', 'Departure')], max_length=10)),
                ('planned_time', models.TimeField()),
                ('PassengersAscending', models.IntegerField()),
                ('PassengersDescending', models.IntegerField()),
            ],
        ),
    ]
