# Generated by Django 6.0.2 on 2026-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintime',
            name='event_type',
            field=models.CharField(choices=[('to_tlv', 'To TLV'), ('from_tlv', 'From TLV')], max_length=10),
        ),
    ]
