# Generated by Django 6.0.2 on 2026-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_times', '0003_backfill_event_type_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_num', models.IntegerField()),
                ('train_station_id', models.IntegerField()),
                ('train_station_order', models.IntegerField()),
                ('train_station_name', models.CharField(max_length=255)),
            ],
        ),
    ]
