# Generated by Django 6.0.2 on 2026-05-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_times', '0004_ranking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
