# Generated by Django 6.0.2 on 2026-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('train_station_name', models.CharField(max_length=255)),
                ('ascending_pass', models.IntegerField()),
                ('descending_pass', models.IntegerField()),
                ('rank', models.CharField(max_length=255)),
            ],
        ),
    ]
