# Generated by Django 6.0.2 on 2026-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_table', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'train_station_name'), name='uniq_ranking_month_station'),
        ),
    ]
