# Generated by Django 6.0.2 on 2026-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_station_name', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('bus_code_name', models.IntegerField()),
                ('bus_station_name', models.CharField(max_length=255)),
                ('officelineid', models.IntegerField()),
                ('line', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('alternative', models.CharField(max_length=255)),
                ('line_type', models.CharField(max_length=255)),
                ('start_stopcode', models.CharField(max_length=255)),
                ('end_stopcode', models.CharField(max_length=255)),
                ('week_period', models.CharField(max_length=255)),
                ('bus_direction', models.CharField(max_length=255)),
            ],
        ),
    ]
