# Generated by Django 6.0.2 on 2026-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix_pass_table', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passengermatrix',
            constraint=models.UniqueConstraint(fields=('from_station_name', 'to_station_name', 'month', 'year'), name='uniq_pass_matrix_pair_month'),
        ),
    ]
